### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by onexdata** [Jam3/get-adobe-generator#1]
Cutting and pasting the example, I get this error, looks like an internal issue where loggerManager isn't defined? Is this project dead, or?

c:\code\generator\node_modules\generator-core\lib\generator.js:85
        this._logger = loggerManager.createLogger("core");
                                     ^

TypeError: Cannot read property 'createLogger' of undefined
    at new Generator (c:\code\generator\node_modules\generator-core\lib\generator.js:85:38)
    at Object.createGenerator (c:\code\generator\node_modules\generator-core\lib\generator.js:102:16)
    at module.exports (c:\code\generator\node_modules\get-adobe-generator\index.js:5:29)
    at Object.<anonymous> (c:\code\generator\index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

**Comment by onexdata** [comment]
I made a pull request to fix the issue (#2 )
